### ISSUE TITLE
"AssertionError: template.id should be defined", when using User.verify method

### ISSUE THREAD

**Issue by poignant-wit** [nidhhoggr/loopback-connector-sparkpost#1] opened 2016-07-19 20:08 UTC
``` javascript
    if (options.template) {
      assert(options.template.id, 'template.id should be defined');
      sparkpostMessage.transmissionBody.substitution_data = options.template.content || [];
      sparkpostMessage.transmissionBody.content.template_id = options.template.id;
    }
```

This block of code conflicts with 'options.template' parameter.

**Comment by nidhhoggr** [comment] 2016-07-19 21:30
Not sure If I understand what the issue is, please elaborate.

**Comment by poignant-wit** [comment] 2016-07-20 07:18
Sorry for my bad english:)
I verify users email using this example: https://docs.strongloop.com/display/public/LB/Registering+users
and i want to send ejs template via sparkpost. I installed 'loopback-connector-sparkpost', configurated it well. In my model 'user' I have code:

```javascript
...
user.afterRemote('create', function(context, userInstance, next) {
    console.log('> user.afterRemote triggered');
 
    var options = {
      type: 'email',
      to: userInstance.email,
      from: 'email@email.com',
      subject: 'Thanks for registering.',
      template: path.resolve(__dirname, '../../server/views/verify.ejs'),
      redirect: '/verified',
      user: user
    };
 
    userInstance.verify(options, function(err, response, next) {
      if (err) return next(err);
 
      console.log('> verification email sent:', response);
 
      context.res.render('response', {
        title: 'Signed up successfully',
        content: 'Please check your email and click on the verification link ' +
            'before logging in.',
        redirectTo: '/',
        redirectToLinkText: 'Log in'
      });
    });
  });

...

```

this dont work. error: "AssertionError: template.id should be defined". Because loopbacks  'userInstance.verify' call connector with 'options.template' <-  ejs template, but connector needs 'template:{id:...}'. so, in connectors source code if i change file 'sparkpost.js' like:
```javascript
    if (options.sparkpostTemplate) {
      assert(options.sparkpostTemplate.id, 'template.id should be defined');
      sparkpostMessage.transmissionBody.substitution_data = options.sparkpostTemplate.content || [];
      sparkpostMessage.transmissionBody.content.template_id = options.sparkpostTemplate.id;
    }

```

, connector works well, and sends verification emails via sparkpost.

**Comment by nidhhoggr** [comment] 2016-09-30 18:08
Should be resolved in latest release, please confirm.

**Closed** 2017-01-12 00:19 UTC
